### ISSUE TITLE
data files are missing

### ISSUE THREAD

**Issue by yasinyildirim** [willdollman/Condensation-Person-Tracker#1]
Hi, 
Could you provide mean.xml and cov.xml data files that the project uses?

**Comment by willdollman** [comment]
Hi! The mean and covariance files make up the "model" of what the background of the scene looks like, so are different for every video you use. As such there isn't a single set of files that I can upload for you to use. The files themselves are generated by a Matlab script, but unfortunately I no longer have a licence.
Hopefully the C code that's already in the repo will be useful though, in getting a basic version of OpenCV's condensation filter working!
